config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'splash/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories, only: [:index, :new, :create, :show] do
    resources :expenses, only: [:index, :new, :create]
  end
  # Defines the root path route ("/")
   root "splash#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can %i[read create], Category
    can %i[index create], Expense
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :icon, presence: true

  belongs_to :user
  has_many :category_expenses, dependent: :destroy
  has_many :expenses, through: :category_expenses, dependent: :destroy
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'

  validates :name, presence: true
  validates :amount, presence: true

  has_many :category_expenses, dependent: :destroy
  has_many :categories, through: :category_expenses, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :expenses, dependent: :destroy, foreign_key: :author_id
  has_many :categories, dependent: :destroy, foreign_key: :user_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  load_and_authorize_resource unless: :devise_controller?
  before_action :devise_allowed_parameters, if: :devise_controller?

  protected

  def devise_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user
    if @category.save
      redirect_to categories_path, notice: 'Category created successfully'
    else
      puts @category.errors.full_messages # Output validation errors to the console
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @category = Category.find(params[:id])
    @expenses = @category.expenses.where(author: current_user)
    @total = @expenses.sum(:amount)
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_category, only: %i[index new create]

  def index
    @expenses = @category.expenses
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.author = current_user

    if @expense.save
      category_ids = params[:expense][:category_ids] || []
      @expense.categories = Category.where(id: category_ids)

      redirect_to @category, notice: 'Expense created successfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!
  skip_load_and_authorize_resource

  def index
    redirect_to categories_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<%= render "shared/nav" %>

<div class="categories">
  <% if @categories.empty? %>
  <div class="get-started">
    <h3 class="started">Get Started</h3>
    <span class="div">Add your first budget by clicking on the button below</span>
  </div>
  <% else %>

  <div class="categories-container">
    <% @categories.each do |category| %>
      <div class="category-card">
        <div class="category-icon">
          <%= image_tag category.icon, alt: 'icon', class: "icon" %>
        </div>
        <div class="card-text">
          <div class="top-card">
            <%= link_to category_path(category.id), style: "text-decoration: none;" do %>
              <p class="category-name"><%= category.name %></p>
            <% end %>
            <p class="amount">$<%= category.expenses.sum(:amount) %></p>
          </div>
          <div class="bottom-card">
            <p class="date"><%= category.created_at.strftime('%d %B, %Y') %></p>
            <p class="user">by <%= current_user.name %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

  </div>
  <div class="fixed-button">
  <div class="text-center link-to">
    <%= link_to 'Add New Category'.html_safe, new_category_path, class: "butt btn-success button-link", style: "color: white;" %>
  </div>
</div>
</div>

app/views/categories/new.html.erb
<%= render "shared/nav" %>
<h1 class="title">Add New Category</h1>

<div class="form-container">
<%= form_with model: @category, url: categories_path, local: true do |f| %>
  <%= f.text_field :name, autofocus: true, placeholder: "Category Name", class:"form-control" %>
  
  <div class="form-group">
    <%= f.label :icon, "Select Icon" %>
    <%= f.collection_select(:icon, [
        ['cash.png', 'Savings 💰'],
        ['hospital.png', 'Medical 👩‍⚕️'],
        ['store.png', 'Shopping 🏪'],
        ['sports.png', 'Activity 🏆'],
        ['beach.png', 'Leisure ⛱️'],
        ['travel.png', 'Travel 🎫'],
        ['other.png', 'Others 📝']
      ], :first, :last, { prompt: 'Select Icon' }, { class: 'form-control' }) %>
  </div>

  <%= f.submit "Save", class:"btn btn-primary sign-up" %>
<% end %>
</div>

app/views/categories/show.html.erb
<%= render "shared/nav" %>

<div class="transactions-container">
  <div class="transactions-title">
    <p class="parr"><%= @category.name %></p>
    <p class="parr">Total: $<%= @category.expenses.sum(:amount) %></p>
  </div>

  <% @expenses.each do |expense| %>
    <div class="transaction-card">
      <div class="category-icon">
        <%= image_tag @category.icon, alt: 'icon', class: "icon" %>
      </div>
      <div class="card-text">
        <div class="name-amount">
          <h4><%= expense.name %></h4>
          <p class="amount">$<%= expense.amount %></p>
        </div>
        <p class="date"><%= expense.created_at.strftime('%d %B, %Y') %></p>
      </div>
    </div>
  <% end %>

  <div class="fixed-button">
    <%= link_to new_category_expense_path(category_id: @category.id) do %>
      <button class="btn btn-success but">Add new transaction</button>
    <% end %>
  </div>
</div>

app/views/expenses/new.html.erb
<%= render "shared/nav" %>

<h3 class="title">Add a new transaction</h3>

<div class="form-container">
  <%= form_with model: @expense, url: category_expenses_path, local: true do |f| %>
    <%= f.text_field :name, autofocus: true, placeholder: "Name", class: "form-control" %>
    <%= f.number_field :amount, autofocus: true, placeholder: "Amount", class: "form-control" %>
    <div class="checkbox-btn">
      <%= f.label :category_ids, "Select one or more categories:" %>
      <div class="checkboxes">
        <%= f.collection_check_boxes :category_ids, current_user.categories, :id, :name do |b| %>
          <div class="form-control">
            <%= b.check_box %>
            <%= b.label %>
          </div>
        <% end %>
      </div>
      
      <%= f.submit "Save", class: "btn btn-primary sign-up" %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-expand-md navbar-dark bg-primary">
  <% if controller_name == 'expenses' && action_name == 'new' %>
    <%= link_to "←", category_path(@category), class: "nav-link" %>
  <% elsif controller_name == 'categories' && (action_name == 'new' || action_name == 'show') %>
    <%= link_to "←", categories_path, class: "nav-link" %>
  <% else %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Categories', categories_path,  class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'New Category', new_category_path,  class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-light' %> 
      </li>
    </ul>
  </div>
  <% end %>
</nav>

app/views/splash/index.html.erb
<div class="splash-container">
  <div class="logo-container">
    <%= image_tag('1802402.png', alt: 'Example image', class: 'logo') %>
    <p class="splashtext min-width: 1">MoneyMinder</p>
  </div>
  <div class="sign-links">
  <%= link_to 'Sign up', new_user_registration_path,  class: 'btn btn-primary sign-up sign-up-btn-boarder sign-up-color' %> 
    <%= link_to 'Log in'.html_safe, new_user_session_path, class: 'log-in' %>
  </div>
</div>
<div class="shadow"></div>